# Generated by Django 5.2.7 on 2025-10-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(help_text='e.g. EdTech Platform, Agri-Tech App', max_length=100)),
                ('short_description', models.TextField(max_length=300)),
                ('price', models.CharField(help_text='e.g. From MWK 1M, Free Tier Available', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('popup_title', models.CharField(blank=True, max_length=120)),
                ('features', models.TextField(help_text='One feature per line. Will be converted to bullet list.')),
                ('stats', models.CharField(blank=True, help_text='e.g. Powering 5K+ students across Malawi.', max_length=150)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
