# Generated by Django 5.2.7 on 2025-10-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(help_text='e.g. React + Django', max_length=100)),
                ('short_description', models.TextField(max_length=300)),
                ('duration', models.CharField(default='6 Months', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('popup_title', models.CharField(blank=True, max_length=150)),
                ('features', models.TextField(help_text='One bullet per line. Will become <li> list.')),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HostingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(help_text='e.g. MWK 15 K/mo or Custom', max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight with scale')),
                ('features', models.TextField(help_text='One feature per line.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hosting Package',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(help_text='e.g. Learning Management', max_length=100)),
                ('short_description', models.TextField(max_length=300)),
                ('price', models.CharField(default='Contact for Pricing', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Software Product',
                'ordering': ['order', 'name'],
            },
        ),
    ]
